services:
  app:
    container_name: bot_franken
    build:
      context: .
      dockerfile: docker/franken/Dockerfile
      network: host
    ports:
      - "81:80"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"
    tty: true

  worker:
    container_name: bot_worker
    build:
      context: .
      dockerfile: docker/franken/Dockerfile
      network: host
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
    command: php bin/console messenger:consume async --time-limit=3600
    restart: on-failure
    depends_on:
      - app

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  caddy_data:
  caddy_config:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
