services:
  caddy:
    container_name: gateway_caddy
    image: ghcr.io/web-udm/white-vpn-gateway:latest
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /var/lib/docker/volumes/gateway_caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory:/etc/caddy-certs:ro
    network_mode: host
    restart: unless-stopped
#test
volumes:
  caddy_data:
  caddy_config: