name: "@telegram"
description: "Telegram bot adapter, no domain layer"
namespace: "App\\Telegram\\"

export:

force-internal:

require:
    - "@subscription"
    - "@user"
    - "@vpn"
    - "#nutgram/nutgram"
    - "#sergix44/container"
    - "#symfony/console"
    - "#symfony/dependency-injection"
    - "#symfony/http-foundation"
    - "#symfony/messenger"
    - "#symfony/routing"

allow-internal-access:
