services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Shared\Infrastructure\Persistence\Doctrine\SqliteWalMiddleware:
        tags:
            - { name: doctrine.middleware }

    SergiX44\Nutgram\Nutgram:
        factory: ['App\Telegram\Infrastructure\NutgramFactory', 'create']
        arguments:
            $token: '%telegram.bot_token%'