# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
imports:
    - { resource: 'instructions.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    SergiX44\Nutgram\Nutgram:
        factory: ['@App\Telegram\Infrastructure\NutgramFactory', 'create']


    App\VPN\Domain\AWGProviderInterface:
        alias: App\VPN\Infrastructure\AWG\WGEasyProvider

