services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    SergiX44\Nutgram\Nutgram:
        factory: ['@App\Telegram\Infrastructure\NutgramFactory', 'create']

