# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    SergiX44\Nutgram\Nutgram:
        factory: ['@App\Telegram\Infrastructure\NutgramFactory', 'create']

    App\VPN\Infrastructure\MTProxy\SyncMtProxySecretsCommand:
        arguments:
            $secretsPath: '%mtproxy.secrets_path%'

    App\VPN\Application\Query\GetVpnConnectionURLs\GetVpnConnectionURLsQueryHandler:
        arguments:
            $mtproxyHost: '%mtproxy.host%'
            $mtproxyPort: '%mtproxy.port%'

