doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            User:
                type: attribute
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: App\User\Domain\Entity
                is_bundle: false
            Subscription:
                type: attribute
                dir: '%kernel.project_dir%/src/Subscription/Domain/Entity'
                prefix: App\Subscription\Domain\Entity
                is_bundle: false

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool