services:
  app:
    container_name: bot_prod_app
    image: ghcr.io/web-udm/white-vpn-bot:prod
    ports:
      - "8080:80"
    env_file: .env
    environment:
      APP_ENV: prod
      SERVER_NAME: ":80"
    volumes:
      - .env:/app/.env
    restart: unless-stopped

  worker:
    container_name: bot_prod_worker
    image: ghcr.io/web-udm/white-vpn-bot:prod
    env_file: .env
    environment:
      APP_ENV: prod
    command: php bin/console messenger:consume async --time-limit=3600
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    depends_on:
      - app

networks:
  default:
    name: whitevpn_db
    external: true
