services:
  app:
    container_name: bot_dev_app
    image: ghcr.io/web-udm/white-vpn-bot:dev
    ports:
      - "8081:80"
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"
    volumes:
      - .env.dev:/app/.env
    restart: unless-stopped

  worker:
    container_name: bot_dev_worker
    image: ghcr.io/web-udm/white-vpn-bot:dev
    env_file: .env.dev
    environment:
      APP_ENV: dev
    command: php bin/console messenger:consume async --time-limit=3600
    volumes:
      - .env.dev:/app/.env
    restart: unless-stopped
    depends_on:
      - app

networks:
  default:
    name: whitevpn_db
    external: true
