services:
  app:
    container_name: bot_franken
    build:
      context: .
      dockerfile: docker/franken/Dockerfile
      network: host
    ports:
      - "81:80"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"
    tty: true

  worker:
    container_name: bot_worker
    build:
      context: .
      dockerfile: docker/franken/Dockerfile
      network: host
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
    command: php bin/console messenger:consume async --time-limit=3600
    restart: on-failure
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:

