name: "@vpn"
description: "VPN provider implementations (3x-ui, etc.)"
namespace: "App\\VPN\\"

export:
  - "App\\VPN\\Port\\"

force-internal:

require:
    - "@subscription"
    - "#"
    - "#doctrine/dbal"
    - "#doctrine/orm"
    - "#doctrine/persistence"
    - "#phpstan/phpstan"
    - "#symfony/console"
    - "#symfony/dependency-injection"
    - "#symfony/http-client"
    - "#symfony/http-client-contracts"
    - "#symfony/maker-bundle"
    - "#symfony/messenger"
    - "#symfony/polyfill-php80"

allow-internal-access:
