services:
  mtproxy:
    build: .
    container_name: mtproxy_app
    volumes:
      - ./secrets.txt:/data/secrets.txt:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - mtproxy_data:/data
    environment:
      MTPROXY_PORT: "${MTPROXY_PORT:-8443}"
      AD_TAG: "${AD_TAG:-}"
    network_mode: host
    restart: unless-stopped


volumes:
  mtproxy_data:
