services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PORT=51821
      - INSECURE=true
      - DISABLE_IPV6=true
      - EXPERIMENTAL_AWG=true
      - OVERRIDE_AUTO_AWG=awg
      - INIT_ENABLED=true
      - INIT_USERNAME=%%WG_USERNAME%%
      - INIT_PASSWORD=%%WG_PASSWORD%%
      - INIT_HOST=awg.whitevpn.tech
      - INIT_PORT=51820
      - INIT_DNS=1.1.1.1,8.8.8.8

volumes:
  etc_wireguard:
