services:
  amneziawg:
    image: ghcr.io/w0rng/amnezia-wg-easy:latest
    container_name: amnezia-wg-easy
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - wireguard:/etc/wireguard
    environment:
      - WG_HOST=awg.whitevpn.tech
      - WG_PORT=51820
      - PORT=51821
      - PASSWORD_HASH=%%AWG_PASSWORD_HASH%%
      - JC=4
      - JMIN=50
      - JMAX=1000
      - S1=50
      - S2=50
      - H1=1234567891
      - H2=1234567892
      - H3=1234567893
      - H4=1234567894

volumes:
  wireguard:
