services:
  relay:
    image: ghcr.io/web-udm/white-vpn-relay:latest
    container_name: relay_caddy
    network_mode: host
    restart: unless-stopped
    environment:
      DEPLOY_HOST: ${DEPLOY_HOST}
      RELAY_VLESS_PORT: ${RELAY_VLESS_PORT}
      RELAY_TROJAN_PORT: ${RELAY_TROJAN_PORT}
      RELAY_SS_PORT: ${RELAY_SS_PORT}
