services:
  relay:
    image: ghcr.io/web-udm/white-vpn-relay:latest
    container_name: relay_caddy
    network_mode: host
    restart: unless-stopped
    environment:
      DEPLOY_HOST: ${DEPLOY_HOST}
      RELAY_VLESS_PORT: ${RELAY_VLESS_PORT}
      RELAY_AWG_PORT: ${RELAY_AWG_PORT}
      RELAY_XHTTP_PORT: ${RELAY_XHTTP_PORT}
      RELAY_GRPC_PORT: ${RELAY_GRPC_PORT}
      RELAY_WS_PORT: ${RELAY_WS_PORT}
      RELAY_HY2_PORT: ${RELAY_HY2_PORT}
