name: Test for Tg-bot

on:
  push:
    branches: [master]
    #paths:
    #  - telegram-bot
  pull_request:
    branches: [master]
    paths:
      - telegram-bot

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build test container
        run: docker compose -f ./telegram-bot/docker-compose-testing.yaml up --remove-orphans -d --build

      - name: Run PHPLint
        run: docker exec bot_franken ./vendor/bin/phplint

      - name: Run PHPStan
        run: docker exec bot_franken php -d memory_limit=512M ./vendor/bin/phpstan analyse

      - name: Run PHPUnit
        run: docker exec bot_franken  ./vendor/bin/phpunit
