name: Test for Tg-bot

on:
  push:
    branches: [master]
    #paths:
    #  - telegram-bot
  pull_request:
    branches: [master]
    paths:
      - telegram-bot

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run PHPStan
        run: docker compose -f ./telegram-bot/docker-compose-testing.yaml run --rm app php vendor/bin/phpstan analyse --memory-limit=512M

      - name: Run PHPUnit
        run: docker compose -f ./telegram-bot/docker-compose-testing.yaml run --rm app vendor/bin/phpunit
